#!/usr/bin/env tsx
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

/**
 * Build script: Load prompts from /prompts directory and generate defaults.ts
 * This runs at build time to embed prompts into the application
 */

const PROMPTS_DIR = process.env.PROMPTS_DIR || '/prompts';
const OUTPUT_DIR = join(process.cwd(), 'src', 'lib', 'prompts');
const OUTPUT_FILE = join(OUTPUT_DIR, 'defaults.ts');

interface PromptDefaults {
  chunkAnalysis: string;
  consolidation: string;
}

function loadPrompts(): PromptDefaults {
  console.log('[load-prompts] Loading prompts from:', PROMPTS_DIR);
  
  try {
    const chunkAnalysis = readFileSync(
      join(PROMPTS_DIR, 'chunk_analysis_prompt.md'),
      'utf-8'
    );
    const consolidation = readFileSync(
      join(PROMPTS_DIR, 'consolidation_prompt.md'),
      'utf-8'
    );

    console.log('[load-prompts] ✓ chunk_analysis_prompt.md:', chunkAnalysis.length, 'chars');
    console.log('[load-prompts] ✓ consolidation_prompt.md:', consolidation.length, 'chars');

    return { chunkAnalysis, consolidation };
  } catch (error) {
    console.error('[load-prompts] ERROR:', error);
    throw error;
  }
}

function generateTypeScript(prompts: PromptDefaults): string {
  return `// Auto-generated by scripts/load-prompts.ts
// DO NOT EDIT MANUALLY - Edit prompts/*.md instead

export const DEFAULT_PROMPTS = {
  chunkAnalysis: ${JSON.stringify(prompts.chunkAnalysis)},
  consolidation: ${JSON.stringify(prompts.consolidation)},
} as const;

export type PromptType = keyof typeof DEFAULT_PROMPTS;
`;
}

function main() {
  console.log('[load-prompts] Starting prompt generation...');
  
  // Ensure output directory exists
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
    console.log('[load-prompts] Created output directory:', OUTPUT_DIR);
  }

  // Load and generate
  const prompts = loadPrompts();
  const typescript = generateTypeScript(prompts);
  
  // Write output
  writeFileSync(OUTPUT_FILE, typescript, 'utf-8');
  console.log('[load-prompts] ✓ Generated:', OUTPUT_FILE);
  console.log('[load-prompts] Done!');
}

main();

